Documentation and program fixes.
* doc-base.sgml:
  + document common practice that value of `Files' field is a space
    separated list of filenames or glob patterns
  + also explicity document the meaning of lines starting with two
    or more spaces
  + add the missing word (closes: #289448)
* install-docs:
  + encode HTML special characters when writing the .dhelp files
    (closes: #114877)
  + correctly handle the verbatim text and blank line for the .dhelp files
  + warn if files refrerred by the doc-base files does not exist.
* Remove ancient stuff from postinst & prerm scripts, remove preinst
  entirelly.
* Use `which' instead of`command -v' in the scripts (closes: #292967).
* debian/copyright: update.
* debian/control: suggest doc-central as an alternative to dhelp or dwww.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -18,10 +18,10 @@ fi
 
 reinstall_docs ( ) {
     # install all the existing doc-base control files
-    num=`ls -1 /usr/share/$package/* | wc -l`
+    num=`find /usr/share/$package/ -maxdepth 1 -type f | wc -l`
     echo "(re)registering $num documents from /usr/share/$package ..." >&2
     for file in /usr/share/$package/*; do
-        install-docs ${VERBOSE} --no-update-menus -i $file || true  # don't abort on failure
+        [ -f $file ] && install-docs ${VERBOSE} --no-update-menus -i $file || true  # don't abort on failure
     done
     if [ -x /usr/bin/update-menus ]; then
         /usr/bin/update-menus
@@ -30,7 +30,7 @@ reinstall_docs ( ) {
 
 case "$1" in
   configure)
-    if [ "${2+set}" != set -o -z "$2" -o "$2" = "<unknown>" ]; then
+    if [ "${2+set}" != set ] || [ -z "$2" ] || [ "$2" = "<unknown>" ]; then
         # first install, or upgrade from ancient version
         reinstall_docs
     elif dpkg --compare-versions $2 lt $compat_ver; then
@@ -44,13 +44,6 @@ case "$1" in
         # only register our stuff
         install-docs ${VERBOSE} --no-update-menus -i /usr/share/$package/$package
         install-docs ${VERBOSE} -i /usr/share/$package/install-docs-man
-    fi
-    if [ -d /usr/lib/menu ]; then
-        files=`find /usr/lib/menu/ -maxdepth 1 -name 'doc-base-*' -type f`
-        if [ "$files" ]; then
-            echo "removing old dwww menu files..." >&2
-            rm -f /usr/lib/menu/doc-base-* || true
-        fi
     fi
     ;;
 esac
diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -12,7 +12,16 @@ if [ "$DEBUG" ]; then
 fi
 
 remove_docs ( ) {
-    if command -v install-docs >/dev/null 2>&1; then
+  if which install-docs >/dev/null 2>&1; then
+    install-docs -r $package || true
+    install-docs -r install-docs-man || true
+  else
+    echo "cannot find install-docs on path" 1>&2
+  fi
+}
+
+remove_all_docs ( ) {
+    if which install-docs >/dev/null 2>&1; then
         echo "unregistering documentation ..."
         for file in /var/lib/doc-base/info/*.status; do
             install-docs -r `basename $file .status` || true
@@ -24,31 +33,18 @@ remove_docs ( ) {
     fi
 }
 
-remove_compat_symlink ( ) {
-    if [ -d /usr/doc ]; then
-	if [ -L /usr/doc/$package ]; then
-	    rm -f /usr/doc/$package
-	fi
-    fi
-}
-
 
 case "$1" in
   remove)
-    remove_docs
-    remove_compat_symlink
+    remove_all_docs
     ;;
   upgrade)
-    remove_compat_symlink
+    remove_docs
     ;;
   failed-upgrade)
     # Prepare to upgrade from version $2 of this package TO THIS VERSION.
     # This is only used if the old version's prerm couldn't handle it,
     # and returned non-zero.  (Fix old prerm bugs here.)
-    if dpkg --compare-versions $2 lt 0.4; then
-	install-docs -r install-docs-man || true
-	install-docs -r install-doc-man || true
-    fi
     ;;
 esac
 
