Improve doc-base manual. Fix quoting in maintainer scripts.
* Improve doc-base manual:
  + enhance the document layout, add some cross references;
  + put an example of PDF and others supported formats (closes: #40912);
  + clarify allowable shell glob patterns (closes: #392587);
  + mention that the registered files should be located under /usr/share/doc
    hierarchy (closes: #333648);
  + review the TODO list.
* Do proper quoting of file names in postinst/postrm scripts
  (closes: #395824)
* install-docs:
  + if glob() returns only one file, check for its existance. glob() seems
    to simply return its argument if it doesn't contain any meta-characters;
  + skip  any doc-base files that contain Version: field, for future
    upgrades.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -21,7 +21,7 @@ reinstall_docs ( ) {
     num=`find /usr/share/$package/ -maxdepth 1 -type f | wc -l`
     echo "(re)registering $num documents from /usr/share/$package ..." >&2
     for file in /usr/share/$package/*; do
-        [ -f $file ] && install-docs ${VERBOSE} --no-update-menus -i $file || true  # don't abort on failure
+        [ -f "$file" ] && install-docs ${VERBOSE} --no-update-menus -i "$file" || true  # don't abort on failure
     done
     if [ -x /usr/bin/update-menus ]; then
         /usr/bin/update-menus
